spring:
  datasource:
    url: jdbc:mysql://localhost:3306/glinde_blog?useUnicode=true&characterEncoding=UTF-8&&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.44.128
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 0

minio:
  endpoint: http://192.168.44.128:9000
  accessKey: admin
  secretKey: 12345678
  bucketName: glinde-blog

server:
  port: 8080